<?php if ($flashes): ?>
                <ul id="flashes">
                    <?php foreach ($flashes as $flash): ?>
                        <li><?php echo $flash; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

<h1>
    <?php if ($_GET['tipo'] == 1): ?>
        Encomendar óleo para stoks
    <?php endif; ?>
    <?php if ($_GET['tipo'] == 2): ?>
        Encomendar óleo para manutenção
    <?php endif; ?>  
</h1>

<form id="change-status-form"  method="post">
    <fieldset>
        
        <div class="field">
            <label>Óleo:</label>
            <select name="oleo" id="oleo" onchange="sub(this)">
                <?php if (array_key_exists('oleo', $_POST) && !array_key_exists('area', $_GET)): ?>
                    <option  value="<?php echo $_POST['oleo']; ?>"><?php echo $oleos->getOleo($_POST['oleo']); ?></option>
                <?php endif; ?>
                <?php foreach ($oleos->getOleos($_SESSION['area']) as $oleo): ?>
                    <option value="<?php echo $oleo['id']; ?>"><?php echo $oleo['Designacao']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Embalagem:</label>
            <select name="embalagem">
                <?php foreach ($oleos->getEmabalagem($oleoID) as $embalagem): ?>
                    <option value="<?php echo $embalagem['id']; ?>"><?php echo $embalagem['Capacidade']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Quantidade:</label>
            <select name="quantidade">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <?php if ($_GET['tipo'] == 2): ?>
            <div class="field">
                <label>Descrição:</label>
                <textarea name="descricao" cols="1" rows="1"></textarea>
            </div>
        <?php endif; ?>
        <div class="wrapper">
            <input type="button" name="encomendar" style="width: 95px" id="login" class="button" value="ENCOMENDAR"/>
        </div>
    </fieldset>
    <input type="hidden" name="palavra" id="palavra"/>
    
</form>

<div id="dialog-form" title="Insira a password do Email">
    <input  type="password" name="password" id="password" class="text"/> 
</div>
