<?php if($_SESSION['user']=='711241'): ?>

<?php if ($flashes): ?>
                <ul id="flashes">
                    <?php foreach ($flashes as $flash): ?>
                        <li><?php echo $flash; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>


<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<h1>Criar Óleo</h1>

<form id='ajaxform1' method="post">
	<fieldset>
        <div class="field">
            <label>Designação:</label>
            <input type="text" name="nome" value="" class="text<?php echo error_field('nome', $errors); ?>"/>
        </div>
         <div class="wrapper">
            <input type="submit" onclick="novo_oleo()" name="save" style="width: 95px"  class="button" value="SUBMETER"/>
        </div>
    </fieldset>
</form>

<?php else: ?>
<h1> Acesso não autorizado! </h1>
<?php endif; ?>