
<?php if (array_key_exists('tipo', $_GET)):?>
<h1>Pesquizar encomendas de lubrificantes</h1>
<?php if($_GET['tipo']==1):?>
<form id='ajaxform1' method="post">    
    <fieldset>
         <div class="field">
            <label>Oleo:</label>
             <select name="search_by_oleo" onchange="get_lub_history();">
                <option>Escolha o óleo</option>
             <?php foreach ($oleo_list as $list): ?>
                <option  value="<?php  echo  $list['ID'] ?>"><?php  echo  $list['Designacao']; ?></option>
             <?php endforeach; ?>
            </select>
        </div>
    </fieldset>
</form>
<?php endif; ?>
<?php if($_GET['tipo']==2):?>
<form id='ajaxform1' method="post">    
    <fieldset>
            <div class="field">
            <label >Data de inicio:</label>
             <input type="text" style="width: 68px" name="dataInicio" id="datainicio" value="" 
                    class="text datepicker"/>
        </div>
        <div class="field">
            <label>Data de fim:</label>
             <input type="text" style="width: 68px" name="dataFim" id="datafim" value="" 
                    class="text datepicker"/>
        </div>
         <div class="wrapper">    
            <input type="button" onclick="get_lub_history();" name="search_by_oleo_date" value="PESQUIZAR" class="submit" />
        </div>
    </fieldset>
</form>
<?php endif; ?>
<?php elseif(true): ?>
<?php if (array_key_exists('search_by_oleo', $_POST)):?>
<h1><?php echo $oleos->getOleo($_POST['search_by_oleo']); ?></h1>
<?php else:?>
    <h1>Encomendas entre <?php echo $_POST['dataInicio']; ?> e <?php echo $_POST['dataFim']; ?></h1>
<?php endif; ?>
<form>
<fieldset>
        <?php foreach ($oleo_history as $oleo): ?>
            <div class="field">
                <label style="width: 130px;">Utilizador:</label>
                <p><?php echo $oleo['Nome'] ?></p>
            </div>
             <div class="field">
                <label style="width: 130px;">Area:</label>
                <p><?php echo $oleo['Area'] ?></p>
            </div>
            <?php  if (array_key_exists('dataInicio', $_POST)): ?>
            <div class="field">
                <label style="width: 130px;">Óleo:</label>
                <p><?php echo $oleo['Designacao'] ?></p>
            </div>
             <?php endif; ?>
              <div class="field">
                <label style="width: 130px;">Capacidade:</label>
                <p><?php echo $oleo['Capacidade'] ?></p>
            </div>
             <div class="field">
                <label style="width: 130px;">Quantidade:</label>
                <p><?php echo $oleo['Qantidade'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de encomenda:</label>
                <p><?php echo $oleo['Data_de_encomenda'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de receção:</label>
                <p><?php echo $oleo['Data_de_rececao'] ?></p>
            </div>
           
           
            &nbsp;
            <p></p>
            <hr size=1>
            &nbsp;
            <p></p>
        <?php endforeach; ?>
    </fieldset>
</form>
<?php endif; ?> 