<h1>Relatório Area C</h1>

<form id="ajaxform1" method="post">
    <div id="tabs" style="margin-top:20px;margin-bottom:20px">
        <ul>
            <li><a href="#1200">U-1200</a></li>
            <li><a href="#1300">U-1300</a></li>
            <li><a href="#1400">U-1400</a></li>
            <li><a href="#1500">U-1500</a></li>
            <li><a href="#1600">U-1600</a></li>
            <li><a href="#1700">U-1700</a></li>
            <li><a href="#10775">U-10775</a></li>
        </ul>
        <div id="1200">
           <?php require "../page/relatorios/area_c/U1200.phtml"; ?>
        </div>



<!-- START OF U-1300 -->




        <div id="1300">
             <table style="width: 100%">

                <td style="width:300px;">
                    <div class="field">
                        <label style="width: 130px;margin-bottom: 75px;">Unidade:</label>
                        <ul style="list-style:none;margin-top:-15px">
                            <li>

                                <input type="radio" name="1300[Unidade]"   value="1">Serciço</input>
                            </li>
                            <li>

                                <input type="radio" name="1300[Unidade]"   value="2">Parada</input>
                            </li>
                            <li>

                                <input type="radio" name="1300[Unidade]"   value="3">Arranque</input>
                            </li>
                            <li>

                                <input type="radio" name="1300[Unidade]"   value="4">Paragem</input>
                            </li>
                            <li>

                                <input type="radio" name="1300[Unidade]"   value="5">Regeneração</input>
                            </li>
                        </ul>
                    </div>
                    
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">FIC1301:</label>
                        <input type="text" name="1300[fic1201]" value="" class="text" style="width:50px"/>
                        m3/h
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">Wait:</label>
                        <input type="text" name="1300[wait]" value="" class="text" style="width:50px"/>
                        m3/h
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">RATIO H2/HC:</label>
                        <input type="text" name="1300[ratio]" value="" class="text" style="width:50px"/>
                        Mol/Mol
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">TIC1311:</label>
                        <input type="text" name="1300[TIC1311]" value="" class="text" style="width:50px"/>
                        ºC
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">FIC1311:</label>
                        <input type="text" name="1300[FIC1311]" value="" class="text" style="width:50px"/>
                        m3/h
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">FIC33701:</label>
                        <input type="text" name="1300[ratio]" value="" class="text" style="width:50px"/>
                        m3/h
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">&Delta; R1301:</label>
                        <input type="text" name="1300[r1301]" value="" class="text" style="width:50px"/>
                        Kg/cm2
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">&Delta; R1302:</label>
                        <input type="text" name="1300[r1302]" value="" class="text" style="width:50px"/>
                        Kg/cm2
                    </div>
                    <div class="field">
                        <label style="width: 110px;margin-bottom: 5px;">&Delta; R1303:</label>
                        <input type="text" name="1300[r1303]" value="" class="text" style="width:50px"/>
                        Kg/cm2
                    </div>
                  
                  
                   
                    <div class="field">
                        <label style="padding-bottom:0px">Energia:</label>
                        <ul style="list-style:none;margin-top:10px">
                            <li>
                                <div class="field">
                                    <label></label>
                                    <label style="width:50px">Incio</label>
                                    <label>Fim</label>

                                </div>
                                <div class="field">
                                    <label>O2R H1301:</label>
                                    <input type="text" name="1300[o2r1301][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[o2r1301][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>pic1354:</label>
                                    <input type="text" name="1300[pic1354][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[pic1354][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>TI1356:</label>
                                    <input type="text" name="1300[TI1356][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[TI1356][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>Consumo Esp.:</label>
                                    <input type="text" name="1300[Consumo1301][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[Consumo1301][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>Eficiência:</label>
                                    <input type="text" name="1300[Eficiência1301][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[Eficiência1301][fim]" value="" class="text" style="width:50px"/>
                                </div>
                            </li>
                        </ul>
                    </div>
                </td>


                <!-- Segunda coluna -->



                <td>
                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">Reformado:</label>
                        <select name="1300[reformado]">
                            <option value="1">Armazenagem</option>
                            <option value="0">Splitter</option>                                        
                        </select>
                    </div>
                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">D-1312:</label>
                        <select name="1300[d1312]">
                            <option value="1">Em Serviço</option>
                            <option value="0">By-pass</option>                                        
                        </select>
                    </div>

                     <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">D-1307:</label>
                        <select name="1300[vapor]">
                            <option value="1">Pressurizado</option>
                            <option value="0">A pressurizar</option>
                            <option value="0">Em manutenção</option>                                        
                        </select>
                    </div>

                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">C-1302:</label>
                        <select name="1300[c1302]">
                            <option value="1">U-1300</option>
                            <option value="0">U-3300</option>                                        
                        </select>
                    </div>

                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">Vapor para C-1301:</label>
                        <select name="1300[vapor]">
                            <option value="1">Col. Geral</option>
                            <option value="0">Paralelo</option>
                            <option value="0">Sobreaquecido</option>                                        
                        </select>
                    </div>

                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">Acetato:</label>
                        <select name="1300[d1312]">
                            <option value="1">Positivo</option>
                            <option value="0">Negativo</option>                                        
                        </select>
                    </div>



                    <div class="field">
                        <label style="width: 130px;margin-bottom: 60px;">Teste Dragger:</label>
                        <ul style="list-style:none;margin-top:-15px">
                            <li>
                              <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">H2 Reciclo:</label>
                              <input type="text" name="1300[dragger][reciclo]" value="" class="text" style="width:50px"/>
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">ppm(CL) M(2ª/4ª/6ª)</label>
                            </li>
                            <li>
                               <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">Saída D-1312:</label>
                              <input type="text" name="1300[dragger][1312]" value="" class="text" style="width:50px"/>
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">ppm(CL) M(Sábado)</label>
                                
                            </li>
                            <li>
                                <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">H2 Reciclo:</label>
                              <input type="text" name="1300[dragger][humidade]" value="" class="text" style="width:50px"/>   
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">ppm(H2O) M(2ª/4ª/6ª)</label>
                              
                                
                            </li>
                            
                        </ul>
                    </div>
                     <div class="field">
                        <label style="width: 130px;margin-bottom: 50px;">P-1302:</label>
                        <ul style="list-style:none;margin-top:-15px">
                            <li>
                              <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">DCP:</label>
                              <input type="text" name="1300[dragger][reciclo]" value="" class="text" style="width:50px"/>
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">cm/min</label>
                            </li>
                            <li>
                               <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">H2O:</label>
                              <input type="text" name="1300[dragger][1312]" value="" class="text" style="width:50px"/>
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">cm/min</label>
                                
                            </li>
                            
                            
                        </ul>
                    </div>
                      <div class="field">
                        <label style="width: 130px;margin-bottom: 20px;">Fosfatos e Hidrazina:</label>
                        <ul style="list-style:none;margin-top:-15px">
                            <li>
                              <label style="width: 80px; margin-bottom: 5px; font-weight: 100;padding-bottom: 0px;">P-1307:</label>
                              <input type="text" name="1300[dragger][reciclo]" value="" class="text" style="width:50px"/>
                              <label style="width: 130px;margin-bottom: 5px;font-weight: 100;padding-bottom: 0px;">cm/min</label>
                            </li>
                            
                        </ul>
                    </div>
                    

                    
                   
                   
                    <div class="field" style="margin-top:20px">
                        <label style="width: 130px;margin-bottom: 0px">Reprocessar LPG:</label>
                        <select name="1300[doctor]">
                            <option value="1">negativo</option>
                            <option value="0">positivo</option>                                        
                        </select>
                    </div>

                    <div class="field">
                        <label style="padding-bottom:0px">Energia:</label>
                        <ul style="list-style:none;margin-top:10px">
                            <li>
                                <div class="field">
                                    <label></label>
                                    <label style="width:50px">Incio</label>
                                    <label>Fim</label>

                                </div>
                                <div class="field">
                                    <label>O2R H1302:</label>
                                    <input type="text" name="1300[o2r1302][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[o2r1302][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>PIC1364:</label>
                                    <input type="text" name="1300[pic1364][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[pic1364][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>TI1364:</label>
                                    <input type="text" name="1300[TI1364][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[TI1364][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>Consumo Esp.:</label>
                                    <input type="text" name="1300[Consumoh1302][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[Consumoh1302][fim]" value="" class="text" style="width:50px"/>
                                </div>
                                <div class="field">
                                    <label>Eficiência:</label>
                                    <input type="text" name="1300[Eficiência1302][inicio]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[Eficiência1302][fim]" value="" class="text" style="width:50px"/>
                                </div>
                            </li>
                        </ul>
                    </div>
                </td>


            </table>
            <div class="field">
                <label style="width: 150px">Qualidade de produtos:</label>

                <ul style="list-style:none">
                    <li>
                        <div class="field">
                            <label style="width:110px"></label>
                            <label style="width:55px">Plano</label>
                            <label style="width:55px">Lab</label>
                            <label>Ações</label>
                        </div>
                        <div class="field">
                                    <label style="width: 110px">GPD (S):</label>
                                    <input type="text" name="1300[gps][plano]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[gps][lab]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[gps][acao]" value="" class="text" style="width:400px"/>
                                </div>
                        <div class="field">
                                    <label style="width: 110px">Gas. Leve (TV):</label>
                                    <input type="text" name="1300[levetv][plano]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[levetv][lab]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[levetv][acao]" value="" class="text" style="width:400px"/>
                                </div>
                        <div class="field">
                                    <label style="width: 110px">Gas. Leva (95%):</label>
                                    <input type="text" name="1300[leve95][plano]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[leve95][lab]" value="" class="text" style="width:50px"/>
                                    <input type="text" name="1300[leve95][acao]" value="" class="text" style="width:400px"/>
                                </div>
                    </li>
                </ul>
            </div>
            <div class="wrapper">

                <input type="submit" onclick="salvar_relatorio();" name="save" value="SALVAR" class="submit" />
        </div>
        <div id="1400">
        </div>
        <div id="1500">
        </div>
        <div id="1600">
        </div>
        <div id="1700">
        </div>
        <div id="10775">
        </div>
    </div>
</form>