<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="../../css/colresize.css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../../css/relatorio.css" rel="stylesheet" type="text/css" />
        <link href="../../css/tabs.css" rel="stylesheet" type="text/css" />


        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="../../css/jquery-ui.css" />
        <script src="../../js/jquery-1.8.3.js"></script>
        <script src="../../js/tabs.js"></script>
        <script src="../../js/jquery-ui.js"></script>

    </head>
    <body>
        <ul style="margin-top:0px">
            <?php foreach ($paginas as $pagina): ?>

                <li>

                    <div class="tabs content" style="font: 11px arial,verdana,sans-serif;width: 880px; height:1270px;border: 2px solid;">
                        <div style="width: 880px;position: absolute;height: 40px;border: 2px solid;border-top: 0px;border-left: 0px;border-right: 0px;">
                            <div style="border-right:  2px solid; width: 293px;position: absolute;height: 40px;"></div>
                            <div style="text-align: center; left:293px;border-right:  2px solid; width: 293px;position: absolute;height: 40px;">
                                <h2 style="margin-bottom: 0px">Relatório Chefe Serviços</h2>
                                <h2 style="margin-bottom: 0px">Area C</h2>
                            </div>
                            <div style=" width: 293px;position: absolute;height: 40px;">

                            </div>
                        </div>
                        <div style="position: relative;margin: 10px;margin-top: 40px;width: 860px; height:1198px;">
                            <form>

                                <?php $relatorios = object_to_array($pagina); ?>

                                <?php for ($i = 0; $i < count($relatorios); $i++): ?>
                                    <?php if ($relatorios != null): ?>
                                        <div class="relatrio-manobra" style="position: absolute;top:<?php echo ($relatorios[$i]['location']['y']); ?>;left:<?php echo $relatorios[$i]['location']['x']; ?>">
                                            <?php print_r($relatorios[$i]['bloco']); ?>
                                        </div>
                                    <?php endif; ?>
                                <?php endfor; ?>
                            </form>
                        </div>
                    </div>
                    <div style="margin-bottom: 5px;width: 880px;height: 42px;border: 2px solid;border-top: 0px">
                        <div style="padding: 5px;border-right:  2px solid; width: 430px;position: absolute;height: 35px;">
                            Elaborado por: Renato Ferreira
                            <span style="float: right">Mec.: 711241</span>
                        </div>
                        <div style="left: 440px;padding: 5px;width: 430px;position: absolute;height: 35px;">
                            Tomei Conhecimento:
                            <span style="float: right">Mec.: 711241</span>
                        </div>
                    </div>

                <?php endforeach; ?>
            </li>
        </ul>
        <script>
            window.print();
        </script>
    </body>
</html>