<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="../../css/colresize.css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../../css/relatorio.css" rel="stylesheet" type="text/css" />
        <link href="../../css/tabs.css" rel="stylesheet" type="text/css" />


        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="../../css/jquery-ui.css" />
        <script src="../../js/jquery-1.8.3.js"></script>
        <script src="../../js/tabs.js"></script>
        <script src="../../js/jquery-ui.js"></script>

    </head>
    <body>
        <ul style="margin-top:0px">
            <?php foreach ($paginas as $pagina): ?>

                <li>

                    <div class="tabs content" style="font: 11px arial,verdana,sans-serif;width: 880px; height:1285px;border: 2px solid;">
                        <div style="width: 880px;position: absolute;height: 40px;border: 2px solid;border-top: 0px;border-left: 0px;border-right: 0px;">
                            <div style="border-right:  2px solid; width: 293px;position: absolute;height: 40px;"></div>
                            <div style="text-align: center; left:293px;border-right:  2px solid; width: 293px;position: absolute;height: 40px;">
                                <h2 style="margin-bottom: 0px">Relatório Chefe Serviços</h2>
                                <h2 style="margin-bottom: 0px"><?php echo $area; ?></h2>
                            </div>
                            <div style="width: 260px;position: absolute;height: 20px;left: 590px;text-align: center;padding: 10px;">
                                <h2 style="float:left;margin-bottom: 0px"><?php echo date('d-m-Y'); ?></h2>
                                <h2 style="margin-bottom: 0px"><?php echo $turno ?></h2>
                                
                            </div>
                        </div>
                        <div style="position: relative;margin: 10px;margin-top: 45px;width: 860px; height:1230px;">
                            <form>

                                <?php $relatorios = object_to_array($pagina); ?>

                                <?php for ($i = 0; $i < count($relatorios); $i++): ?>
                                    <?php if ($relatorios != null): ?>
                                        <div class="relatrio-manobra" style="position: absolute;top:<?php echo ($relatorios[$i]['location']['y']); ?>;left:<?php echo $relatorios[$i]['location']['x']; ?>">
                                            <?php print_r($relatorios[$i]['bloco']); ?>
                                        </div>
                                    <?php endif; ?>
                                <?php endfor; ?> 
                                <?php foreach ($separadores as $separador): ?>
                                    <?php $s = object_to_array($separador); ?>
                                    <?php if ($s['pagina'] == $count && $s != ''): ?>
                                        <div class="relatrio-manobra" style="position: absolute;top:<?php echo $s['top']; ?>px;left:-10px">
                                            <div  class="draggable"><div style="width:880px;border-top: 1px solid"></div></div>
                                        </div>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                <?php $count++; ?>
                            </form>
                        </div>
                    </div>
                    <div style="margin-bottom: 5px;width: 880px;height: 40px;border: 2px solid;border-top: 0px">
                        <div style="padding: 5px;border-right:  2px solid; width: 430px;position: absolute;height: 30px;">
                            Elaborado por: <?php echo $_SESSION['user_name']; ?>
                            <span style="float: right">Mec.: <?php echo $_SESSION['user'];?></span>
                        </div>
                        <div style="left: 445px;padding: 5px;width: 430px;position: absolute;height: 30px;">
                            Tomei Conhecimento:

                        </div>
                    </div>

                <?php endforeach; ?>
            </li>
        </ul>
        <script>
            window.print();
        </script>
    </body>
</html>