<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="../../css/colresize.css" />
        <link href="../../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../../css/relatorio.css" rel="stylesheet" type="text/css" />
        <link href="../../css/tabs.css" rel="stylesheet" type="text/css" />


        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="../../css/jquery-ui.css" />
        <script src="../../js/jquery-1.8.3.js"></script>
        <script src="../../js/tabs.js"></script>
        <script src="../../js/jquery-ui.js"></script>

    </head>
    <body>
        <div class="tabs content" style="font: 11px arial,verdana,sans-serif;width: 880px; height:1335px;border: 2px solid;">
            <div style="width: 880px;position: absolute;height: 40px;border: 2px solid;border-top: 0px;border-left: 0px;border-right: 0px;">
                <div style="border-right:  2px solid; width: 293px;position: absolute;height: 40px;"></div>
                <div style="text-align: center; left:293px;border-right:  2px solid; width: 293px;position: absolute;height: 40px;">
                    <h2 style="margin-bottom: 0px">Relatório Chefe Serviços</h2>
                    <h2 style="margin-bottom: 0px">Area C</h2>
                </div>
                <div style=" width: 293px;position: absolute;height: 40px;">

                </div>
            </div>
            <div style="margin: 10px;position:relative;width: 860px; height:1280px;">
                <form>
                    <?php foreach ($relatorio as $bloco): ?>
                        <?php
                        $array = object_to_array($bloco);
                        $bloco = object_to_array($array);
                        ?>
                        <?php if ($bloco != null): ?>
                            <div class="relatrio-manobra" style="position: absolute;top:<?php echo $bloco['location']['y']; ?>;left:<?php echo $bloco['location']['x']; ?>">
                                <?php print_r($bloco['bloco']); ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php foreach ($separadores as $separador): ?>
                        <?php
                        $array = object_to_array($separador);
                        $bloco = object_to_array($array);
                        ?>
                        <?php if ($bloco != null): ?>
                            <div class="relatrio-manobra" style="position: absolute;top:<?php echo $bloco['top']; ?>px;left:-10px">
                                <div  class="draggable"><div style="width:880px;border-top: 1px solid"></div></div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </form>
            </div>
            <div style="position: absolute;float: left;left: 0px;top:1290px;width: 882px;height: 40px;border-top: 2px solid">
                <div style="padding: 5px;border-right:  2px solid; width: 430px;position: absolute;height: 35px;">
                    Elaborado por: Renato Ferreira
                    <span style="float: right">Mec.: 711241</span>
                </div>
                <div style="left: 440px;padding: 5px;width: 430px;position: absolute;height: 35px;">
                    Tomei Conhecimento:
                    <span style="float: right">Mec.: 711241</span>
                </div>
            </div>
        </div>
        <script>
            window.print();
        </script>
    </body>
</html>