<?php
$unidadesdao = new UnidadesDao();
$unidades = $unidadesdao->findUnidades($_SESSION['area']);
?>
<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 698px;">
        <div class="field">
            <input type="button" name="alterar" onclick="relatorio('novobloco');" style="margin-top: 5px;margin-bottom: 5px;float: left" value="Novo Bloco" class="button">
            <input type="button" name="alterar" onclick="" style="margin-top: 5px;float: left" value="Separador" class="button">
            <input type="button" name="alterar" onclick="" style="margin-top: 5px;float: left" value="Salvar" class="button">
            <input type="button" name="alterar" onclick="relatorio('imprimir');" style="margin-top: 5px;float: left;" value="Imprimir" class="button">
        </div> 
    </fieldset>
</form>
<div id="containment-wrapper">

</div>

<div id="dialog-novobloco" title="Novo Bloco">
    <form>
        <fieldset>
            <div class="field">
                <label>Unidade:</label>
                <select name="unidade">
                    <?php foreach ($unidades as $unidade): ?>
                        <option value="<?php echo $unidade['id'] ?>">
                            <?php echo $unidade['designacao']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="field">
                <label>Tipo:</label>
                <select name="tipo" onchange="relatorio(this);">
                    <option value="1">
                        Escolha multipla
                    </option>
                    <option value="2">
                        Introdução de valores simples
                    </option>
                    <option value="3">
                        Introdução de valores multiplos
                    </option>
                    <option value="4">
                        Tabela
                    </option>
                </select>
            </div>
            <div class="field">
                <label>Titulo:</label>
                <input type="text" style="width: 250px" name="equipamento"/>
            </div>
            <div id="multipla" style="display: none;">
                <div class="field">
                    <label>Escolha1:</label>
                    <input type="text" style="width: 250px" name="escolha1"/>
                    <input type="button" name="adicionar" onclick="relatorio(this);" style="font-weight: bolder;width: 20px;height: 16px;margin-top: 2px;padding-bottom: 1px;"  value="+" class="button">
                </div>
            </div>
            <div id="tabela" style="dysplay:block;">
                <div class="field">
                    <label>Linhas:</label>
                    <select id="linhas" onchange="relatorio(this)">
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>
                </div>
                <div class="field">
                    <label>Colunas:</label>
                    <select id="colunas" onchange="relatorio(this)">
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>
                </div>
                <div class="field">

                    <table id="MatrixTable"  width="500" border="0" cellpadding="0" cellspacing="0">
                        <tbody id="MatrixTableBody">
                        <tr>
                            <td ></td><td><input type="text"/></td><td ><input type="text"/></td>
                        </tr>
                        <tr>
                            <td ><input type="text"/></td><td>cell</td><td c>cell</td>
                        </tr>
                        <tr>
                            <td><input type="text"/></td><td>cell</td><td>cell</td>
                        </tr>			
                        </tbody>
                    </table>
                </div>
            </div>
        </fieldset>
    </form>
</div>

