<?php
$unidadesdao = new UnidadesDao();
$unidades = $unidadesdao->findUnidades($_SESSION['area']);
?>
<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 860px;">
        <div class="field">
            <input type="button" name="alterar" onclick="relatorio('novobloco');" style="margin-top: 5px;margin-bottom: 5px;float: left" value="Novo Bloco" class="button">
            <input type="button" name="alterar" onclick="relatorio('separador');" style="margin-top: 5px;float: left" value="Separador" class="button">
            <input type="button" name="alterar" onclick="relatorio('salvar');" style="margin-top: 5px;float: left" value="Salvar" class="button">
            <input type="button" name="alterar" onclick="relatorio('imprimir');" style="margin-top: 5px;float: left;" value="Imprimir" class="button">
        </div> 
    </fieldset>
</form>
<div id="containment-wrapper">
    
</div>

<div id="dialog-novobloco" title="Novo Bloco">
    <form>
        <fieldset>
            <div class="field">
                <label>Unidade:</label>
                <select id="unidade" name="unidade">
                    <?php foreach ($unidades as $unidade): ?>
                        <option value="<?php echo $unidade['id'] ?>">
                            <?php echo $unidade['designacao']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="field">
                <label>Tipo:</label>
                <select id="tipo" name="tipo" onchange="relatorio(this);">
                    <option value="4">
                        Tabela
                    </option>
                    <option value="1">
                        Escolha multipla
                    </option>
                    <option value="2">
                        Introdução de valores
                    </option>


                </select>
            </div>
            <div class="field">
                <label>Titulo:</label>
                <input type="text" style="width: 250px" id="titulo" name="titulo"/>
            </div>
            <div id="bloco">
                <div id="multipla" style="display:none;">

                </div>
                <div id="valores" style="display:none;">

                </div>
                <div id="tabela" style="display:block;">

                </div>
            </div>
        </fieldset>
    </form>
</div>
<div id="dialog-inserirnomestabbela" title="Novo Bloco">
    
        <fieldset>
            <div class="field">
                <label>Nome do campo:</label>
                <input id="nomecampo" type="text"/>
            </div>
        </fieldset>
    
</div>