<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">
            
            <input type="button" name="alterar" onclick="relatorio('salvar_relatorio');" style="background-image: url(img/buttons/save.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Salvar" class="button">
            <input type="button" name="alterar" onclick="relatorio('imprimir');" style="background-image: url(img/buttons/b_print.png);margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>

<h1 style="margin-top: 30px">Relatório Area C</h1>

<form id="salvarRelatorioForm" method="post">
    
    <ul id="tab1" class="tabs">

    </ul>
</form>