<form >
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">

            <input type="button" name="nova_versao" onclick="relatorio(this);" style="background-image: url(img/buttons/b_table_add.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Criar nova versão" class="button">
            <input type="button" name="alterar" onclick="relatorio('imprimir');" style="background-image: url(img/buttons/b_print.png);margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>

<h1 style="margin-top: 30px">Versões dos templates dos relatórios</h1>

<form>

    <fieldset>
        <?php foreach ($versoes as $versao): ?>
            <div class="field">
                <label style="width: 100px;">Versão:</label>
                <p><?php echo $versao['versao']; ?></p>
            </div>
            <div class="field">
                <label style="width: 100px;">Data:</label>
                <p><?php echo $versao['data']; ?></p>
            </div>
            <div class="field">
                <label style="width: 100px;">Criador:</label>
                <p><?php echo $versao['username']; ?></p>
            </div>
            <?php if ($versao['status'] == 1): ?>
                <h2 style="color: red;margin-bottom: 0px;clear: left;">Versão em uso!</h2>
            <?php endif; ?>
            <input type="button" name="editar_versao" versao="<?php echo $versao['versao']; ?>" onclick="relatorio(this);" style="background-image: url(img/buttons/b_edit.png);clear: left;margin-bottom: 10px;margin-top: 10px;float: left;" value="Editar" class="button">
            <?php if ($versao['status'] == 0): ?>
                <input type="button" name="set_as_default" versao="<?php echo $versao['versao']; ?>" onclick="relatorio(this);" style="background-image: url(img/buttons/s_success.png);margin-bottom: 10px;margin-top: 10px;float: left;" value="Defenir como principal" class="button">
            <?php endif; ?>
            &nbsp;
            <p></p>
            <div class="clear separator"></div>
            &nbsp;
            <p></p>
        <?php endforeach; ?>
    </fieldset>
</form>

<div id="dialog-novaversao" title="Nova versão">
    <form id="ajaxform1" method="post">
        <ul>
            <li>
                <input type="radio" name="tipo" value="1" style="float: left;"/><p>Abrir um template limpo</p>
            </li>
            <li>
                <input type="radio" name="tipo" value="2" style="float: left;"/><p>Criar a partir de uma das seguintes versões:</p>
                <select name='versao'>
                    <?php foreach ($versoes as $versao): ?>
                        <option><?php echo $versao['versao']; ?></option>
                    <?php endforeach; ?>
                </select>
            </li>
        </ul>
    </form>

</div>