<!DOCTYPE html>
<html>
    <head>
        <title>Site FCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="css/colresize.css" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/default.css" rel="stylesheet" type="text/css" />
        <link href="css/relatorio.css" rel="stylesheet" type="text/css" />
        <link href="css/tabs.css" rel="stylesheet" type="text/css" />

        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="css/jquery-ui.css" />
        <script src="js/jquery-1.8.3.js"></script>
        <script src="js/tabs.js"></script>
        <script src="js/equipamento.js"></script>
        <script src="js/jquery-ui.js"></script>
        <script src="js/script.js"></script>
        <script src="js/app.js"></script>
        <script src="js/relatorio.js"></script>
        <script src="js/processo.js"></script>
        <script src="js/moment.js"></script>
        <script src="js/colResizable-1.5.min.js"></script>
        <script src="js/jquery.form.js"></script>
        <script src="js/ckeditor/ckeditor.js"></script>
        <script src="js/ckeditor/samples/js/sample.js"></script>
        <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
        <script type="text/javascript" src="js/jquery.weekpicker.js"></script>
        

        <!--<script src="js/jquery.tinyscrollbar.js"></script>-->
        <script type="text/javascript">
             ( function( factory ) {
    if ( typeof define === "function" && define.amd ) {

        // AMD. Register as an anonymous module.
        define( [ "../widgets/datepicker" ], factory );
    } else {

        // Browser globals
        factory( jQuery.datepicker );
    }
}( function( datepicker ) {

datepicker.regional.pt = {
    closeText: "Fechar",
    prevText: "Anterior",
    nextText: "Seguinte",
    currentText: "Hoje",
    monthNames: [ "Janeiro","Fevereiro","Março","Abril","Maio","Junho",
    "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" ],
    monthNamesShort: [ "Jan","Fev","Mar","Abr","Mai","Jun",
    "Jul","Ago","Set","Out","Nov","Dez" ],
    dayNames: [
        "Domingo",
        "Segunda-feira",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado"
    ],
    dayNamesShort: [ "Dom","Seg","Ter","Qua","Qui","Sex","Sáb" ],
    dayNamesMin: [ "Dom","Seg","Ter","Qua","Qui","Sex","Sáb" ],
    weekHeader: "Sem",
    dateFormat: "dd/mm/yy",
    firstDay: 0,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "" };
datepicker.setDefaults( datepicker.regional.pt );

return datepicker.regional.pt;

} ) );
 


            $(document).ready(function () {
                $.fn.textWidth = function (text, font) {
                    if (!$.fn.textWidth.fakeEl)
                        $.fn.textWidth.fakeEl = $('<span>').hide().appendTo(document.body);
                    $.fn.textWidth.fakeEl.text(text || this.val() || this.text()).css('font', font || this.css('font'));
                    return $.fn.textWidth.fakeEl.width();
                };
                $('#accordion').accordion({
                    heightStyle: "content"
                });
            });

            function showscroll(obj) {
                $("#feed").css("overflow", "auto");
            }

            function hidescrooll() {
                $("#feed").css("overflow", "hidden");
            }
            $.fn.scrollTo = function (target, options, callback) {
                if (typeof options == 'function' && arguments.length == 2) {
                    callback = options;
                    options = target;
                }
                var settings = $.extend({
                    scrollTarget: target,
                    offsetTop: 50,
                    duration: 500,
                    easing: 'swing'
                }, options);
                return this.each(function () {
                    var scrollPane = $(this);
                    var scrollTarget = (typeof settings.scrollTarget == "number") ? settings.scrollTarget : $(settings.scrollTarget);
                    var scrollY = (typeof scrollTarget == "number") ? scrollTarget : scrollTarget.offset().top + scrollPane.scrollTop() - parseInt(settings.offsetTop);
                    scrollPane.animate({scrollTop: scrollY}, parseInt(settings.duration), settings.easing, function () {
                        if (typeof callback == 'function') {
                            callback.call(this);
                        }
                    });
                });
            }

        </script>
        <script>
        jQuery(document).ready(function ($) {
            
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,$Opacity:2}
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 600);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>

        <style>
            #dvLoading {
                display: none;
                position: fixed;
                z-index: 1000;
                top: 0;
                left: 0;
                height: 100%;
                width: 100%;
                background: rgba( 255, 255, 255, .8) url('img/ajax-loader.gif') 50% 50% no-repeat;
            }
            .dropdown-content {
                display: none;
                position: absolute;
                z-index: 100000;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);

            }
            #noticias { margin: 0 0 0 20px; clear: both; }
            #noticias a:link, #noticias a:visited { background-image: url(img/dotted.jpg); background-repeat: repeat-x; background-position: bottom left; width: 375px; display: block; padding: 10px 0 12px 0; }
            #noticias a.ultimo:link,  a.ultimo:visited { background-image: none; }
            #noticias .data { font-weight: bold; color: #333; padding: 0 2px 0 0; }
            #noticias .cat { font-weight: bold; color: #FA4616; text-transform: uppercase; padding: 0 0 0 6px; background: url(img/li-preto.gif) no-repeat 0 -4px; }
            #noticias .desc { display: block; line-height: 18px; }
            #noticias .estilo-link { color: #FA4616; float: right; margin: 0 10px 10px 0; }
            #noticias a:hover { text-decoration: none; background-color: #FAF5F1; }

            .noticia-detalhes { position: relative; top: -7px; }
            .noticia-detalhes li { float: left; background: url(img/li-laranja.gif) no-repeat 6px 0px; color: #000; font-weight: bold; }
            .noticia-detalhes li.primeiro { background: none; padding: 0; }
            .noticia-detalhes li.cat a:link, .noticia-detalhes li.cat a:visited { text-transform: uppercase; text-decoration: none; color: #666; }
            .noticia-detalhes li.cat a:hover { text-decoration: underline; }
            .noticia-detalhes li.cat { font-weight: normal; padding-left: 14px}
            .noticia-detalhes li.data { color: #FA4616; }

        </style>
         <style>
        
        /* jssor slider bullet navigator skin 05 css */
        /*
        .jssorb05 div           (normal)
        .jssorb05 div:hover     (normal mouseover)
        .jssorb05 .av           (active)
        .jssorb05 .av:hover     (active mouseover)
        .jssorb05 .dn           (mousedown)
        */
        .jssorb05 {
            position: absolute;
        }
        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
            position: absolute;
            /* size of bullet elment */
            width: 16px;
            height: 16px;
            background: url('img/slide/b05.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb05 div { background-position: -7px -7px; }
        .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
        .jssorb05 .av { background-position: -67px -7px; }
        .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }

        /* jssor slider arrow navigator skin 12 css */
        /*
        .jssora12l                  (normal)
        .jssora12r                  (normal)
        .jssora12l:hover            (normal mouseover)
        .jssora12r:hover            (normal mouseover)
        .jssora12l.jssora12ldn      (mousedown)
        .jssora12r.jssora12rdn      (mousedown)
        */
        .jssora12l, .jssora12r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 30px;
            height: 46px;
            cursor: pointer;
            background: url('img/slide/a12.png') no-repeat;
            overflow: hidden;
        }
        .jssora12l { background-position: -16px -37px; }
        .jssora12r { background-position: -75px -37px; }
        .jssora12l:hover { background-position: -136px -37px; }
        .jssora12r:hover { background-position: -195px -37px; }
        .jssora12l.jssora12ldn { background-position: -256px -37px; }
        .jssora12r.jssora12rdn { background-position: -315px -37px; }
    </style>


    </head>
    <body>
        <div id="dvLoading" class="dvLoading"></div>
        <div id="wrapper" >
            <div id="topheader">
                <?php if (array_key_exists('error', $_GET)): ?>
                    <?php echo 'Utilizador ou password errada!'; ?>
                <?php elseif (array_key_exists('request', $_GET)): ?>
                    <?php echo 'Pedido enviado com sucesso!'; ?>
                <?php elseif (array_key_exists('newuser', $_GET)): ?>
                    <?php echo 'Novo utilizador adicionado com sucesso!'; ?>
                <?php elseif (array_key_exists('user', $_SESSION)): ?>
                    <form id="ajaxform4" method="post" style="float:left;width: 300px;">
                        <label style="with:110px;margin-top: 5px;padding-bottom: 0px;">Area de trabalho:</label>
                        <select name="area" onchange="submit_area(this)">
                            <?php while (list($key, $val) = each($user['area'])): ?>
                                <option value="<?php echo $key; ?>" <?php if (array_key_exists('area', $_POST)) if ($_POST['area'] == $key) echo 'selected'; ?>>
                                    <?php echo $val; ?>
                                </option>
                            <?php endwhile; ?>
                        </select>
                    </form>
                <?php endif ?>
                <div style="float: right;"><?php if (array_key_exists('user', $_SESSION)) echo $_SESSION['user_name'] . '&nbsp;&nbsp;|&nbsp;&nbsp;<a href="index.php/sair" style="text-decoration: underline;cursor: default;">Sair</a>' ?></div>
            </div>
            <div id="main-menu">
                <ul>
                    <li class="primeiro"><a href="http://www.galpenergia.com/PT/agalpenergia/Paginas/GalpEnergiaRelance.aspx" onclick="target = '_blank'" title="A Galp Energia num relance">A Galp Energia num Relance</a></li>
                    <li><a href="plataforma.html" title="A Plataforma PortalFCA">  A Refinaria de Matosinhos </a></li>
                    <li onmouseout="$('#submenu').css('display', 'none')" onmouseover="$('#submenu').css('display', 'block')"><a href="" title="A Plataforma PortalFCA">A Fábrica de Combustíveis e Aromáticos</a>
                        <div id="submenu" class="dropdown-content">
                            <ul>
                                <li class="primeiro">
                                    <a href="equipa.html" title="A equipa FCA">Missão/Visão</a>
                                </li>
                                <li>
                                    <a href="equipa.html" title="A equipa FCA">A Instalação</a>
                                </li>
                                <li>
                                    <a href="equipa.html" title="A equipa FCA">A Equipa</a>
                                </li>
                                <li>
                                    <a href="equipa.html" title="A equipa FCA">MAQSE</a>
                                </li>
                                <li>
                                    <a href="equipa.html" title="A equipa FCA">Excelência Operacional</a>
                                </li>
                                <li class="ultimo">
                                    <a href="equipa.html" title="A equipa FCA">Inovação e Criação de Valor</a>
                                </li>
                            </ul>
                        </div>
                    </li>

                </ul>
            </div>
            <div id="header">
                <a href="http://www.galpenergia.com" id="logo" onclick="target = '_blank'" title="Galp Energia">Galp logo site </a>
                <h1 class="title"><a href="login.html" title="PortalFCA">Site FCA</a></h1>
            </div>
            <?php require $template ?>
            <div id="footer" style="position: absolute;width: 1100px;bottom: 3px">

                <div class="clear separator"></div>
                <ul>
                    <li><a href="http://www.galpenergia.com/PT/Contactos/Paginas/Contactos.aspx" onclick="target = '_blank'">Contactos</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/SugestoesReclamacoes.aspx" onclick="target = '_blank'">Sugestões e reclamações</a></li>
                    <li><a href="http://www.galpenergia.com/PT/QuestoesFrequentes" onclick="target = '_blank'">Perguntas frequentes</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Mapa.aspx" onclick="target = '_blank'">Mapa do site</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Acessibilidade.aspx" onclick="target = '_blank'">Acessibilidade</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/NotasLegais.aspx" onclick="target = '_blank'">Notas legais</a></li>
                    <li class="none"><a href="http://www.galpenergia.com/PT/Paginas/Privacidade.aspx" onclick="target = '_blank'">Privacidade</a></li>
                </ul>
                <div id="copy"><script type="text/javascript" src="js/copy.js"></script></div>
            </div>
        </div>
        <script>
                        var username = '<?php if (array_key_exists('user', $_SESSION)) echo $_SESSION['user_name'] ?>';
                        var userid = '<?php if (array_key_exists('user', $_SESSION)) echo $_SESSION['user'] ?>'
        </script>
    </body>
</html>