<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="css/colresize.css" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/default.css" rel="stylesheet" type="text/css" />
        <link href="css/relatorio.css" rel="stylesheet" type="text/css" />
        <link href="css/tabs.css" rel="stylesheet" type="text/css" />

        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="css/jquery-ui.css" />
        <script src="js/jquery-1.8.3.js"></script>
        <script src="js/tabs.js"></script>
        <script src="js/equipamento.js"></script>
        <script src="js/jquery-ui.js"></script>
        <script src="js/script.js"></script>
        <script src="js/app.js"></script>
        <script src="js/relatorio.js"></script>
        <script src="js/processo.js"></script>
        <script  src="js/colResizable-1.5.min.js"></script>
        <script src="js/jquery.form.js"></script>
        <script src="js/ckeditor/ckeditor.js"></script>
        <script src="js/ckeditor/samples/js/sample.js"></script>

        <!--<script src="js/jquery.tinyscrollbar.js"></script>-->
        <script type="text/javascript">
            $(document).ready(function () {
                $.fn.textWidth = function (text, font) {
                    if (!$.fn.textWidth.fakeEl)
                        $.fn.textWidth.fakeEl = $('<span>').hide().appendTo(document.body);
                    $.fn.textWidth.fakeEl.text(text || this.val() || this.text()).css('font', font || this.css('font'));
                    return $.fn.textWidth.fakeEl.width();
                };
                $('#accordion').accordion({
                    heightStyle: "content"
                });
            });

            function showscroll(obj) {
                $("#feed").css("overflow", "auto");
            }

            function hidescrooll() {
                $("#feed").css("overflow", "hidden");
            }

        </script>

        <style>
            #noticias { margin: 0 0 0 20px; clear: both; }
            #noticias a:link, #noticias a:visited { background-image: url(../img/dotted.jpg); background-repeat: repeat-x; background-position: bottom left; width: 375px; display: block; padding: 10px 0 12px 0; }
            #noticias a.ultimo:link,  a.ultimo:visited { background-image: none; }
            #noticias .data { font-weight: bold; color: #333; padding: 0 2px 0 0; }
            #noticias .cat { font-weight: bold; color: #f37020; text-transform: uppercase; padding: 0 0 0 6px; background: url(../img/li-preto.gif) no-repeat 0 -4px; }
            #noticias .desc { display: block; line-height: 18px; }
            #noticias .estilo-link { color: #f37020; float: right; margin: 0 10px 10px 0; }
            #noticias a:hover { text-decoration: none; background-color: #FAF5F1; }

            .noticia-detalhes { position: relative; top: -7px; }
            .noticia-detalhes li { float: left; background: url(../img/li-laranja.gif) no-repeat 6px 0px; color: #000; font-weight: bold; }
            .noticia-detalhes li.primeiro { background: none; padding: 0; }
            .noticia-detalhes li.cat a:link, .noticia-detalhes li.cat a:visited { text-transform: uppercase; text-decoration: none; color: #666; }
            .noticia-detalhes li.cat a:hover { text-decoration: underline; }
            .noticia-detalhes li.cat { font-weight: normal; padding-left: 14px}
            .noticia-detalhes li.data { color: #F37020; }

        </style>

        <style>
            .dvLoading {
                display: none;
                position: fixed;
                z-index: 1000;
                top: 0;
                left: 0;
                height: 100%;
                width: 100%;
                background: rgba( 255, 255, 255, .8) url('img/ajax-loader.gif') 50% 50% no-repeat;
            }
            .historico{
                width: 700px;
                padding: 5px;
            }
            .historico td{
                padding: 2px;
            }
            #circularG{
                position:relative;
                width:37px;
                height:37px;
                //margin: auto;
            }

            .circularG{
                position:absolute;
                background-color:rgb(0,0,0);
                width:9px;
                height:9px;
                border-radius:6px;
                -o-border-radius:6px;
                -ms-border-radius:6px;
                -webkit-border-radius:6px;
                -moz-border-radius:6px;
                animation-name:bounce_circularG;
                -o-animation-name:bounce_circularG;
                -ms-animation-name:bounce_circularG;
                -webkit-animation-name:bounce_circularG;
                -moz-animation-name:bounce_circularG;
                animation-duration:0.718s;
                -o-animation-duration:0.718s;
                -ms-animation-duration:0.718s;
                -webkit-animation-duration:0.718s;
                -moz-animation-duration:0.718s;
                animation-iteration-count:infinite;
                -o-animation-iteration-count:infinite;
                -ms-animation-iteration-count:infinite;
                -webkit-animation-iteration-count:infinite;
                -moz-animation-iteration-count:infinite;
                animation-direction:normal;
                -o-animation-direction:normal;
                -ms-animation-direction:normal;
                -webkit-animation-direction:normal;
                -moz-animation-direction:normal;
            }

            #circularG_1{
                left:0;
                top:15px;
                animation-delay:0.268s;
                -o-animation-delay:0.268s;
                -ms-animation-delay:0.268s;
                -webkit-animation-delay:0.268s;
                -moz-animation-delay:0.268s;
            }

            #circularG_2{
                left:4px;
                top:4px;
                animation-delay:0.364s;
                -o-animation-delay:0.364s;
                -ms-animation-delay:0.364s;
                -webkit-animation-delay:0.364s;
                -moz-animation-delay:0.364s;
            }

            #circularG_3{
                top:0;
                left:15px;
                animation-delay:0.45s;
                -o-animation-delay:0.45s;
                -ms-animation-delay:0.45s;
                -webkit-animation-delay:0.45s;
                -moz-animation-delay:0.45s;
            }

            #circularG_4{
                right:4px;
                top:4px;
                animation-delay:0.536s;
                -o-animation-delay:0.536s;
                -ms-animation-delay:0.536s;
                -webkit-animation-delay:0.536s;
                -moz-animation-delay:0.536s;
            }

            #circularG_5{
                right:0;
                top:15px;
                animation-delay:0.632s;
                -o-animation-delay:0.632s;
                -ms-animation-delay:0.632s;
                -webkit-animation-delay:0.632s;
                -moz-animation-delay:0.632s;
            }

            #circularG_6{
                right:4px;
                bottom:4px;
                animation-delay:0.718s;
                -o-animation-delay:0.718s;
                -ms-animation-delay:0.718s;
                -webkit-animation-delay:0.718s;
                -moz-animation-delay:0.718s;
            }

            #circularG_7{
                left:15px;
                bottom:0;
                animation-delay:0.814s;
                -o-animation-delay:0.814s;
                -ms-animation-delay:0.814s;
                -webkit-animation-delay:0.814s;
                -moz-animation-delay:0.814s;
            }

            #circularG_8{
                left:4px;
                bottom:4px;
                animation-delay:0.9s;
                -o-animation-delay:0.9s;
                -ms-animation-delay:0.9s;
                -webkit-animation-delay:0.9s;
                -moz-animation-delay:0.9s;
            }



            @keyframes bounce_circularG{
                0%{
                    transform:scale(1);
                }

                100%{
                    transform:scale(.3);
                }
            }

            @-o-keyframes bounce_circularG{
                0%{
                    -o-transform:scale(1);
                }

                100%{
                    -o-transform:scale(.3);
                }
            }

            @-ms-keyframes bounce_circularG{
                0%{
                    -ms-transform:scale(1);
                }

                100%{
                    -ms-transform:scale(.3);
                }
            }

            @-webkit-keyframes bounce_circularG{
                0%{
                    -webkit-transform:scale(1);
                }

                100%{
                    -webkit-transform:scale(.3);
                }
            }

            @-moz-keyframes bounce_circularG{
                0%{
                    -moz-transform:scale(1);
                }

                100%{
                    -moz-transform:scale(.3);
                }
            }
        </style>
    </head>
    <body>
        <div id="dvLoading" class="dvLoading"></div>
        <div id="wrapper" >
            <div id="topheader">
                <?php if (array_key_exists('error', $_GET)): ?>
                    <?php echo 'Utilizador ou password errada!'; ?>

                <?php elseif (array_key_exists('user', $_SESSION)): ?>
                    <form id="ajaxform4" method="post" style="float:left;width: 300px;">
                        <label style="margin-top: 5px;padding-bottom: 0px;">Area de trabalho:</label>
                        <select name="area" onchange="submit_area(this)">
                            <?php while (list($key, $val) = each($user['area'])): ?>
                                <option value="<?php echo $key; ?>" <?php if (array_key_exists('area', $_POST)) if ($_POST['area'] == $key) echo 'selected'; ?>>
                                    <?php echo $val; ?>
                                </option>
                            <?php endwhile; ?>
                        </select>
                    </form>
                <?php endif ?>
                <div style="float: right;"><?php if (array_key_exists('user', $_SESSION)) echo $_SESSION['user_name'] . '&nbsp;&nbsp;|&nbsp;&nbsp;<a href="index.php/sair" style="text-decoration: underline;cursor: default;">Sair</a>' ?></div>
            </div>
            <div id="main-menu">
                <ul>
                    <li><a href="trabalhar_na_fca.html" title="Trabalhar na FCA">Trabalhar na FCA</a></li>
                    <li><a href="plataforma.html" title="A Plataforma PortalFCA">A Plataforma PortalFCA</a></li>
                    <li><a href="equipa.html" title="A equipa FCA">A equipa FCA</a></li>
                    <li><a href="http://www.galpenergia.com/PT/agalpenergia/Paginas/GalpEnergiaRelance.aspx" onclick="target = '_blank'" title="A Galp Energia num relance">A Galp Energia num Relance</a></li>
                </ul>
            </div>
            <div id="header">
                <a href="http://www.galpenergia.com" id="logo" onclick="target = '_blank'" title="Galp Energia">Galp logo site </a>
                <h1 class="title"><a href="login.html" title="PortalFCA">PortalFCA</a></h1>
            </div>
            <?php require $template ?>
            <div id="footer" style="position: absolute;width: 1100px;bottom: 3px">

                <div class="clear separator"></div>
                <ul>
                    <li><a href="http://www.galpenergia.com/PT/Contactos/Paginas/Contactos.aspx" onclick="target = '_blank'">Contactos</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/SugestoesReclamacoes.aspx" onclick="target = '_blank'">Sugestões e reclamações</a></li>
                    <li><a href="http://www.galpenergia.com/PT/QuestoesFrequentes" onclick="target = '_blank'">Perguntas frequentes</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Mapa.aspx" onclick="target = '_blank'">Mapa do site</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Acessibilidade.aspx" onclick="target = '_blank'">Acessibilidade</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/NotasLegais.aspx" onclick="target = '_blank'">Notas legais</a></li>
                    <li class="none"><a href="http://www.galpenergia.com/PT/Paginas/Privacidade.aspx" onclick="target = '_blank'">Privacidade</a></li>
                </ul>
                <div id="copy"><script type="text/javascript" src="js/copy.js"></script></div>
            </div>
        </div>

    </body>
</html>