<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../css/default.css" rel="stylesheet" type="text/css" />
         
        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="../css/jquery-ui.css" />
        <script src="../js/jquery-1.8.3.js"></script>
        <script src="../js/jquery-ui.js"></script>
        <script src="../js/script.js"></script>
        <script src="../js/app.js"></script>
        <script src="../js/jquery.form.js"></script>

        <style>
             .dropdown-content {
                display: none;
                position: absolute;
                z-index: 100000;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
               
            }
        </style>


    </head>
    <body>
        <div id="dvLoading" class="dvLoading"></div>
        <div id="wrapper" >
            <div id="topheader">
            </div>
            <div id="main-menu">
                <ul>
                    <li class="primeiro"><a href="http://www.galpenergia.com/PT/agalpenergia/Paginas/GalpEnergiaRelance.aspx" onclick="target = '_blank'" title="A Galp Energia num relance">A Galp Energia num Relance</a></li>
                    <li><a href="plataforma.html" title="A Plataforma PortalFCA">  A Refinaria de Matosinhos </a></li>
                    <li onmouseout="$('#submenu').css('display', 'none')" onmouseover="$('#submenu').css('display', 'block')"><a href="" title="A Plataforma PortalFCA">A Fábrica de Combustíveis e Aromáticos</a>
                        <div id="submenu" class="dropdown-content">
                            <ul>
                            <li class="primeiro">
                                <a href="equipa.html" title="A equipa FCA">Missão/Visão</a>
                            </li>
                            <li>
                                <a href="equipa.html" title="A equipa FCA">A Instalação</a>
                            </li>
                            <li>
                                <a href="equipa.html" title="A equipa FCA">A Equipa</a>
                            </li>
                            <li>
                                <a href="equipa.html" title="A equipa FCA">MAQSE</a>
                            </li>
                            <li>
                                <a href="equipa.html" title="A equipa FCA">Excelência Operacional</a>
                            </li>
                            <li class="ultimo">
                                <a href="equipa.html" title="A equipa FCA">Inovação e Criação de Valor</a>
                            </li>
                        </ul>
                        </div>
                    </li>

                </ul>
            </div>
            <div id="header">
                <a href="http://www.galpenergia.com" id="logo" onclick="target = '_blank'" title="Galp Energia">Galp logo site </a>
                <h1 class="title"><a href="login.html" title="PortalFCA">Site FCA</a></h1>
            </div>
            <div style="margin-left: 350px; ">
                <h1>Reset de PassWord</h1>
                <?php if (!empty($errors)): ?>
                    <ul class="errors">
                        <?php foreach ($errors as $error): ?>
                            <?php /* @var $error Error */ ?>
                            <li>
                                <?php echo $error->getMessage(); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <form action="lostpass" method="post">
                    <fieldset>
                       
                        <div class="field">
                            <label style="width: 120px">Numero Mec.:</label>
                            <input type="text" style="width: 100px" name="numero"  />
                        </div>
                       
                        &nbsp; &nbsp;
                        <div class="wrapper">
                            <input type="submit" style="float: left" name="signin" onclick="$('#dvLoading').show();" style="width: 95px" id="signin" class="button" value="Pedir" />
                        </div>
                    </fieldset>
                </form>
            </div>
            <div id="footer" style="position: absolute;width: 1100px;bottom: 3px">

                <div class="clear separator"></div>
                <ul>
                    <li><a href="http://www.galpenergia.com/PT/Contactos/Paginas/Contactos.aspx" onclick="target = '_blank'">Contactos</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/SugestoesReclamacoes.aspx" onclick="target = '_blank'">Sugestões e reclamações</a></li>
                    <li><a href="http://www.galpenergia.com/PT/QuestoesFrequentes" onclick="target = '_blank'">Perguntas frequentes</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Mapa.aspx" onclick="target = '_blank'">Mapa do site</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Acessibilidade.aspx" onclick="target = '_blank'">Acessibilidade</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/NotasLegais.aspx" onclick="target = '_blank'">Notas legais</a></li>
                    <li class="none"><a href="http://www.galpenergia.com/PT/Paginas/Privacidade.aspx" onclick="target = '_blank'">Privacidade</a></li>
                </ul>
                <div id="copy"><script type="text/javascript" src="../js/copy.js"></script></div>
            </div>
        </div>

    </body>
</html>



