<!DOCTYPE html>
<html>
    <head>
        <title>PortalFCA</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../css/default.css" rel="stylesheet" type="text/css" />

        <!--<link rel="stylesheet" type="text/css" href="css/colresize.css" /> -->
        <link rel="stylesheet" href="../css/jquery-ui.css" />
        <script src="../js/jquery-1.8.3.js"></script>
        <script src="../js/jquery-ui.js"></script>
        <script src="../js/script.js"></script>
        <script src="../js/app.js"></script>
        <script src="../js/jquery.form.js"></script>




    </head>
    <body>
        <div id="dvLoading" class="dvLoading"></div>
        <div id="wrapper" >
            <div id="topheader">
            </div>
            <div id="main-menu">
                <ul>
                    <li><a href="trabalhar_na_fca.html" title="Trabalhar na FCA">Trabalhar na FCA</a></li>
                    <li><a href="plataforma.html" title="A Plataforma PortalFCA">A Plataforma PortalFCA</a></li>
                    <li><a href="equipa.html" title="A equipa FCA">A equipa FCA</a></li>
                    <li><a href="http://www.galpenergia.com/PT/agalpenergia/Paginas/GalpEnergiaRelance.aspx" onclick="target = '_blank'" title="A Galp Energia num relance">A Galp Energia num Relance</a></li>
                </ul>
            </div>
            <div id="header">
                <a href="http://www.galpenergia.com" id="logo" onclick="target = '_blank'" title="Galp Energia">Galp logo site </a>
                <h1 class="title"><a href="login.html" title="PortalFCA">PortalFCA</a></h1>
            </div>
            <div style="margin-left: 350px; ">
                <h1>Novo Utilizador</h1>
                <?php if (!empty($errors)): ?>
                    <ul class="errors">
                        <?php foreach ($errors as $error): ?>
                            <?php /* @var $error Error */ ?>
                            <li>
                                <?php echo $error->getMessage(); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <form action="signin" method="post">
                    <fieldset>
                        <div class="field">
                            <label>Nome:</label>
                            <input type="text" style="width: 200px" name="utilizador[nome]" value="" class="text"/>
                        </div>
                        <div class="field">
                            <label>Numero Mec:</label>
                            <input type="text" style="width: 68px" name="utilizador[numero]" value="" class="text" />
                        </div>
                        <div class="field">
                            <label>PassWord:</label>
                            <input type="password" style="width: 150px" name="utilizador[pass]" class="" />
                        </div>
                        <div class="field">
                            <label>Area(s):</label>
                            <input type="checkbox" name="option1" value="1">Area A</input>
                            &nbsp;
                            <input type="checkbox" name="option2" value="2">Area B</input>
                            &nbsp;
                            <input type="checkbox" name="option3" value="3">Area C</input>
                            &nbsp;
                            <input type="checkbox" name="option4" value="4">Area D</input>

                        </div>
                        &nbsp; &nbsp;
                        <div class="wrapper">
                            <input type="submit" name="signin" onclick="$('#dvLoading').show();" style="width: 95px" id="signin" class="button" value="Inscrever" />
                        </div>
                    </fieldset>
                </form>
            </div>
            <div id="footer" style="position: absolute;width: 1100px;bottom: 3px">

                <div class="clear separator"></div>
                <ul>
                    <li><a href="http://www.galpenergia.com/PT/Contactos/Paginas/Contactos.aspx" onclick="target = '_blank'">Contactos</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/SugestoesReclamacoes.aspx" onclick="target = '_blank'">Sugestões e reclamações</a></li>
                    <li><a href="http://www.galpenergia.com/PT/QuestoesFrequentes" onclick="target = '_blank'">Perguntas frequentes</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Mapa.aspx" onclick="target = '_blank'">Mapa do site</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/Acessibilidade.aspx" onclick="target = '_blank'">Acessibilidade</a></li>
                    <li><a href="http://www.galpenergia.com/PT/Paginas/NotasLegais.aspx" onclick="target = '_blank'">Notas legais</a></li>
                    <li class="none"><a href="http://www.galpenergia.com/PT/Paginas/Privacidade.aspx" onclick="target = '_blank'">Privacidade</a></li>
                </ul>
                <div id="copy"><script type="text/javascript" src="../js/copy.js"></script></div>
            </div>
        </div>

    </body>
</html>


