<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">
            <input type="button" onclick="processo(this);" name="comentar" style="margin-bottom: 5px;margin-top: 5px;float: left" value="Comentar" class="button">
            <input type="button" onclick="processo(this);" name="comentarios" style="width: 110px;margin-bottom: 5px;margin-top: 5px;float: left" value="Ver comentários" class="button">
            <input type="button" name="imprimir" onclick="processo('imprimir');" style="margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>


<h1 style="margin-top: 30px"><?php echo $manobras['nome']; ?></h1>

<form id="ajaxform1" method="post">
    <div class="field">
        <label>Unidade:</label>
        <p><?php echo $manobras['unidade']; ?></p>
    </div>
    <div class="field">
        <label>Descrição:</label>
        <div style="margin-left: 100px">
            <?php echo json_decode($manobras['descricao']); ?>
        </div>
    </div>
    <div class="field">
        <label>Procedimentos:</label>
    </div>
    <div  class="field">
        <table id="procedimentos" style="width: 700px">

        </table>
    </div>

</form>

<div id="dialog-aceitar-manobra" title="Aceitar">
    <p style="width: 250px;">Tem de aceitar todos os passos!</p> 
</div>
<div id="dialog-alerta" title="Atenção!">
    <p style="width: 250px;" id="alerta_mensagem"></p> 
</div>
<div id="dialog-unidades" title="Unidades">
    <form id="salvarRelatorioForm" method="post">


    </form>
</div>

<div id="dialog-status-equipamento" title="Status do equipamento">
    <form id="salvarStatusEquipamneto">
        <ul id="tab2" class="tabs"></ul>
    </form>
</div>


<div id="dialog-alterar-status" title="Alterar Status">
    <h1 style="margin-bottom: 20px;" id="equipamento_status"></h1>
    <form>
        <fieldset id="dialog_elements">
            <div  class="field">
                <label style="width: 120px">Novo status:</label>
                <select onchange="equipamento_dinamico(this);" id="halt-status">
                    <option value="1">Parada - Disponível</option>
                    <option value="2">Parada - Indisponível</option>
                    <option value="3">Parada - Em Manutenção</option>
                    <option value="4">Em Serviço</option>
                    <option value="5">Em Serviço - Com anomalia</option>
                    <option value="6">Em Serviço - Em observação</option>
                    </select>
            </div>
        </fieldset>
    </form>
</div>
<div id="dialog-unidades" title="Unidades">
    <form id="salvarRelatorioForm" method="post">
    </form> 
</div>