<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">
            <input type="button" proc_id="<?php echo $manobras['id']; ?>" onclick="processo(this,null);" name="editar_proc" style="margin-bottom: 5px;margin-top: 5px;float: left" value="Editar" class="button">
            <input type="button" onclick="processo(this);" name="comentar" style="margin-bottom: 5px;margin-top: 5px;float: left" value="Comentar" class="button">
            <input type="button" onclick="processo(this);" name="comentarios" style="width: 110px;margin-bottom: 5px;margin-top: 5px;float: left" value="Ver comentários" class="button">
            <input type="button" name="imprimir" proc_id="<?php echo $manobras['id']; ?>" onclick="processo(this);" style="margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>


<h1 style="margin-top: 30px"><?php echo $manobras['nome']; ?></h1>

<form id="ajaxform1" method="post">
    <div class="field">
        <label>Unidade:</label>
        <p><?php echo $manobras['unidade']; ?></p>
    </div>
    <div class="field">
        <label>Descrição:</label>
        <div style="margin-left: 100px">
            <?php echo json_decode($manobras['descricao']); ?>
        </div>
    </div>
    <div class="field">
        
    </div>
    <div  class="field">
        <label>Procedimentos:</label>
        <table id="procedimentos" style="margin-left: 5px;width: 850px;clear: both;">

        </table>
    </div>

</form>


<div id="dialog-alerta" title="Atenção!">
    <p style="width: 250px;" id="alerta_mensagem"></p> 
</div>
<div id="dialog-unidades" title="Unidades">
    <form id="salvarRelatorioForm" method="post">
    

    </form>
</div>

<div id="dialog-status-equipamento" title="Status do equipamento">
    <form id="salvarStatusEquipamneto">
        
    </form>
</div>

