<h1>Nova Manobra Processual</h1>

<form id="adicionarManobraForm" method="post">
    <fieldset>
        
        <div class="field">
            <label>Unidade:</label>
            <select id="unidade" name="unidade">
                <?php foreach ($unidades as $unidade): ?>
                <option 
                    <?php 
                      if(array_key_exists('unidade', $_GET)) if($_GET['unidade']==$unidade['id']) echo ' selected '; 
                    ?> 
                    value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao'];?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Nome:</label>
            <input type="text" style="width: 400px" name="nome"/>
        </div>
         <div class="field">
            <label style="width:200px;margin-top: 10px;">Passos da manobra:</label>
            
        </div>
        <div id="passos">
         <div class="field">
            <label>Passo 1:</label>
            <textarea rows="4" cols="60" name="passos[passo1]"></textarea>
        </div>
        </div>
         <div class="field">
            
            <input type="button" onclick="processo(this);" name="nova_manobra" value="Adicionar passo" class="submit" style="float:left;width: 100px;margin-bottom: 10px;margin-top: 10px;margin-left: 0px;" />
        </div>
         <div class="field">
        <input type="button" style="float: left;width: 100px;margin-top: 10px;margin-bottom: 10px;" onclick="processo(this);" id="ocultar" name="ocultar" value="Ocultar relatório" class="submit" />
    </div>
         <div id="relatorio" style="margin-bottom: 5px; margin-top: 35px; width: 690px;height: 400px;position: relative;">
         
         </div>
         <div class="wrapper">
            
            <input type="button" onclick="processo(this);" name="adicionar" value="<?php echo 'ADICIONAR'; ?>" class="submit" />
        </div>
     </fieldset>
  </form>