<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">
            <input type="button" onclick="processo(this);" name="novo_passo" style="background-image: url(img/buttons/b_export.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Adicionar passo" class="button">
            <input type="button" onclick="processo(this);" name="novo_titulo" style="background-image: url(img/buttons/b_ftext.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Adicionar titulo" class="button">
            <input type="button" onclick="processo(this);" name="salvar" style="background-image: url(img/buttons/save.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Salvar" class="button">
            <input type="button" onclick="processo(this);" name="eliminar_proc" style="background-image: url(img/buttons/b_drop.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Eliminar" class="button">
            <input type="button" onclick="processo(this);" name="simular" style="background-image: url(img/buttons/play.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Simular" class="button">
            <input type="button" onclick="processo(this);" name="maximizar" style="background-image: url(img/buttons/viewInFullscreen.png);padding-left: 25px;margin-bottom: 5px;margin-top: 5px;float: left" value="Maximizar editor" class="button">
            <input type="button" name="alterar" onclick="processo('imprimir');" style="background-image: url(img/buttons/b_print.png);margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>


<h1 style="margin-bottom: 10px;margin-top: 30px">Novo Procedimento</h1>

<form id="adicionarManobraForm" method="post">
    <fieldset>

        <div class="field">
            <label>Unidade:</label>
            <select id="unidade" name="manobra[unidade]">
                <?php foreach ($unidades as $unidade): ?>
                    <option 
                    <?php
                    if (array_key_exists('unidade', $_GET))
                        if ($_GET['unidade'] == $unidade['id'])
                            echo ' selected ';
                    ?> 
                        value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Nome:</label>
            <input type="text" style="text-align:left; width: 400px" id="manobra_nome" name="manobra[nome]"/>
        </div>
        <div class="field">
            <label>Publicar:</label>
            <select id="publicar" name="publicar">
                <option value="0">Não</option>
                <option value="1">Sim</option>
            </select>
        </div>
        <div class="field">
            <label>Descrição:</label>
            <input type="hidden" name="texto" id="texto"/>
            <div  onmouseover="stopScroll()" onmouseout="showScroll()" style="margin-left: 97px">
            <div  id="editor">

              
            </div>
            </div>
        </div>
        <div class="field">
            <label style="width:200px;margin-top: 10px;">Passos do procedimento:</label>

        </div>
        <div id="passos">
            
        </div>
        <input type="hidden" id="proc_id" name="id"/>


        <!--<div class="clear separator"></div>-->


    </fieldset>
</form>

<div id="dialog-alertas" title="Novo Alerta">
    <form >
        <fieldset>
            <div class="field">
                <label style="padding-bottom: 20px;">Alerta:</label>
                <input type="checkbox" id="alerta_ralatorio" name="relatorio" value="1"> Alertar para alterar relatório<br>
                <input type="checkbox" id="alerta_equipamento" name="equipmento" value="2"> Alertar para alterar estado de equipamento<br>
                <input type="button" onclick="processo(this);" id="adicionar_equipamento" name="adicionar_equipamento" index="' + index + '" value="Adicionar equipamento" class="submit" style="float:none; width: 150px;margin:0px;margin-top: 10px;" />
                <input type="hidden"  id="equipamento_value"  />
             </div>
            <div style="margin-top: 30px" class="field">
                <label>Mensagem:</label>
                <textarea style="height: 70px;width: 309px;" id="mensagem" name="manobra[passos][passo1]"></textarea>
            </div>
        </fieldset>
    </form>
</div>

<div id="dialog-add-title" title="Adicionar titulo">
    <form >
        <fieldset>
            <div class="field">
                <label style="padding-bottom: 20px;">Passo:</label>
                <select id="position-title">
                    
                </select>
             </div>
        </fieldset>
         
    </form>
     O titulo será adicionado antes do passo indicado
</div>

<div id="dialog-move-item" title="Mover">
    <form >
        <fieldset>
            <div class="field">
                <label style="padding-bottom: 20px;">Posição:</label>
                <select id="position-step">
                    
                </select>
             </div>
        </fieldset>
    </form>
</div>

<div id="dialog-listar-equipamento" title="Status do equipamento">
    <form id="salvarStatusEquipamneto">
        
    </form>
</div>
<div id="dialog-informacao" title="Informação">
    <label id="informacao">
        
    </label>
</div>


<div id="dialog-warning" title="Aviso!">
    <label>Deseja continuar?</label>
</div>