
<form id="ajaxform1" method="post">
    <fieldset style="z-index: 100; position: fixed;background-color: rgb(243,243,243);width: 863px;">
        <div class="field">
            
            <input type="button" onclick="processo(this);" name="salvar_nova_rotina" style="background-image: url(img/buttons/save.png);margin-bottom: 5px;margin-top: 5px;float: left" value="Salvar" class="button">
            
            <input type="button" onclick="processo(this);" name="maximizar" style="background-image: url(img/buttons/viewInFullscreen.png);padding-left: 25px;margin-bottom: 5px;margin-top: 5px;float: left" value="Maximizar editor" class="button">
            <input type="button" name="alterar" onclick="processo('imprimir');" style="background-image: url(img/buttons/b_print.png);margin-top: 5px;float: left;" value="Imprimir" class="button">

        </div> 
    </fieldset>
</form>
<h1 style="margin-top: 30px">Nova Rotina</h1>

<form id="adicionarRotinaForm" method="post">
    <fieldset>

        <div class="field">
            <label>Unidade:</label>
            <select id="unidade" name="unidade">
                <?php foreach ($unidades as $unidade): ?>
                    <option 
                    <?php
                    if (array_key_exists('unidade', $_GET))
                        if ($_GET['unidade'] == $unidade['id'])
                            echo ' selected ';
                    ?> 
                        value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Nome:</label>
            <input type="text" style="text-align:left;width: 400px" id="manobra_nome" name="nome"/>
        </div>
        <div class="field" style="margin-bottom:10px">
            <label>Descrição:</label>
            <input type="hidden" name="texto" id="texto"/>
            <div  onmouseover="stopScroll()" onmouseout="showScroll()" style="margin-left: 97px">
            <div  id="editor">

              
            </div>
            </div>
        </div>

         <div class="field">
            <label>Alerta:</label>
            <textarea name="alerta"></textarea>
        </div>
        
        <div class="field" style="margin-top: 10px">
            <label>Frequencia:</label>
            <select style="float: left" name="frequencia" onchange="processo(this)">
                <option value="1">Diária</option>
                <option value="2">Semanal</option>
                <option value="3">Mensal</option>
                
            </select>
            <ul style="float: left;margin-left: 5px">
                <li>
                    <input name="manha" type="checkbox" >Manhã
                </li>
                <li>
                    <input name="tarde" type="checkbox">Tarde
                </li>
                <li>
                    <input name="noite" type="checkbox">Noite
                </li>
            </ul>
        </div>
       


        <!--<div class="clear separator"></div>-->


    </fieldset>
</form>
<div id="dialog-informacao" title="Informação">
    <label id="informacao">
        
    </label>
</div>