<h1>Horas de marcha do Equipamento</h1>

<form id="ajaxform1" method="post">
    <fieldset>
        
        <div class="field">
            <label>Unidade:</label>
            <select name="horas" onchange="subChangeEquipamentoUnidaded(this)">
                <?php foreach ($unidades as $unidade): ?>
                <option 
                    <?php 
                      if(array_key_exists('unidade', $_GET)) if($_GET['unidade']==$unidade['id']) echo ' selected '; 
                      if (array_key_exists('unidade', $_POST)) {
                          if($_POST['unidade']==$unidade['id']) echo ' selected ';
                      }
                    ?> 
                    value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao'];?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
         <div class="field" style="margin-top: 20px;">
            
            <label style="width: 120px;margin-left: 100px;">Total de horas</label>
            <label style="width: 100px;">Este mês</label>
            <label style="width: 250px;">Status</label>
        </div>
        
        <?php foreach ($horas as $hora): ?>
        <div class="field">
            <label><?php echo $hora['equipamento']['Equipamento'].':' ?></label>
            <p style="margin-left:5px;width: 120px;float: left;"><?php echo $hora['total'] ?></p>
            <p style="float: left;width: 100px;"><?php echo $hora['mes'] ?></p>
            <?php if($hora['equipamento']['estado']=='5'){
                $estado='Serviço';
            }
            else{
                $estado='Parada';
            }
            ?>
            <p><?php echo $estado;?></p>
        </div>
        <?php endforeach; ?>

        
     </fieldset>
  </form>