<?php if ($flashes): ?>
    <ul id="flashes">
        <?php foreach ($flashes as $flash): ?>
            <li><?php echo $flash; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>


<h1>
    <?php if ($edit): ?>
        <?php echo Utils::escape($autorizacao->getNumero()); ?>
    <?php else: ?>
        Adicionar nova autorização
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
    <ul class="errors">
        <?php foreach ($errors as $error): ?>
            <?php /* @var $error Error */ ?>
            <li><?php echo $error->getMessage(); ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>


<form id="ajaxform1" method="post">
    <fieldset>
        <div class="field">
            <label>Numero:</label>
            <input type="text" id="numero_aut" name="autorizacao[numero]" value="<?php
            if (array_key_exists('firma', $_GET))
                echo $_POST['autorizacao']['numero'];
            elseif (array_key_exists('edit', $_GET))
                echo Utils::escape($autorizacao->getNumero());
            ?>"
                   class="text<?php echo error_field('numero', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Unidade:</label>
            <select name="autorizacao[unidade]">
                <?php foreach ($unidades as $unidade): ?>
                    <option 
                    <?php
                    if (array_key_exists('firma', $_GET))
                        if ($_POST['autorizacao']['unidade'] == $unidade['id'])
                            echo ' selected ';
                        elseif (array_key_exists('edit', $_GET))
                            if ($autorizacao->getUnidade() == $unidade['id'])
                                echo ' selected ';
                    ?> 
                        value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Equipamento:</label>
            <select name="pedido[equipamento]" onchange="show_pedidos(this)">
                <option></option>
<?php foreach ($equipamentos as $equipamento): ?>
                    <option 
                        value="<?php echo $equipamento['id'] ?>"><?php echo $equipamento['Equipamento']; ?>
                    </option>
<?php endforeach; ?>
            </select>
        </div>
        <div class="hiddenbox">

            <label style=" width: 200px;">Pedidos trabalho associados:</label>
            <ul id="trab_list">

            </ul>
            <input type="hidden" id="pedido" value="-1" name="pedido"/>

        </div>
        <div class="field">
            <label>Tipo:</label>
            <select name="autorizacao[tipo]">
                <option <?php if (array_key_exists('firma', $_GET))
    if ($_POST['autorizacao']['tipo'] == 1)
        echo ' selected ';
    elseif (array_key_exists('edit', $_GET))
        if ($autorizacao->getTipo() == 1)
            echo ' selected ';
?> value="1">Vermelha</option>
                <option <?php if (array_key_exists('firma', $_GET))
                    if ($_POST['autorizacao']['tipo'] == 2)
                        echo ' selected ';
                    elseif (array_key_exists('edit', $_GET))
                        if ($autorizacao->getTipo() == 2)
                            echo ' selected ';
?>value="2">Amarela</option>
            </select>
        </div>
        <div class="field">
            <label>Firma:</label>
            <select name="autorizacao[firma]">
<?php if (array_key_exists('firma', $_GET)): ?>
                    <option value="<?php echo $id ?>"><?php echo $_GET['firma'] ?></option>
<?php endif; ?>
<?php
$firmas = new firmaDao();
foreach ($firmas->getFirmas() as $firma):
    ?>
                    <option value="<?php echo $firma->getID(); ?>"><?php echo $firma->getNome(); ?></option>
<?php endforeach; ?>       
            </select>
            <input type="button" id="nova_firma" name="save" style="width:100px;margin-right:245px;margin-top:-1px" value="Nova Firma" class="submit">
        </div>
        <div class="field">
            <label>Validade:</label>
            <input type="text" style="width: 68px" name="autorizacao[dataInicio]" id="data" value="<?php echo Utils::escape($dueOn->format('Y-n-j')); ?>" 
                   class="text datepicker"/>
            &nbsp;
            <select name="autorizacao[dataFim]">
                <option>7</option>
                <option>30</option>
            </select>
            &nbsp;
            Dias
        </div>

        <div class="field">
            <label>Descrição:</label>
            <textarea id="descricao_trabalho" name="autorizacao[texto]" cols="1" rows="1" style="width:400px" class="<?php echo error_field('texto', $errors); ?>"><?php if (array_key_exists('firma', $_GET)) echo $_POST['autorizacao']['texto'];elseif (array_key_exists('edit', $_GET)) echo Utils::escape($autorizacao->getTexto()); ?></textarea>
        </div>
        <div class="wrapper">

            <input type="submit" onclick="add_edit_aut();" name="save" value="<?php echo $edit ? 'EDITAR' : 'ADICIONAR'; ?>" class="submit" />
        </div>
    </fieldset>
</form>

<div id="dialog-nova-firma" title="Insira nome da firma">
    <input  type="text" name="firma" id="firma" class="text"/> 
</div>