<?php if ($_GET['tipo'] == 1): ?>
    <h1>Caducadas sem registo</h1>
<?php endif; ?>
<?php if ($_GET['tipo'] == 2): ?>
    <h1>Trabalhos em curso</h1>
<?php endif;?>
<?php if ($_GET['tipo'] == 3): ?>
    <h1>Trabalhos do dia</h1>
<?php endif; 
?>



<form id="ajaxform1" method="post">
    <fieldset>
        <?php foreach ($trabalhos as $trabalho): ?>
            <div class="field">
                <label style="width: 130px;">Numero:</label>
                <?php if ($trabalho['tipo'] == 1): ?>
                    <p style="color: red"><?php echo Utils::stringrpl(3, ' ', Utils::stringAddZero($trabalho['Numero'])); ?></p>
                <?php endif; ?>
                <?php if ($trabalho['tipo'] == 2): ?>
                    <p style="color: gold"><?php echo Utils::stringrpl(3, ' ', Utils::stringAddZero($trabalho['Numero'])); ?></p>
                <?php endif; ?>
            </div>
            <div class="field">
                <label style="width: 130px;">Descrição:</label>
                <p><?php echo $trabalho['Descricao'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Firma:</label>
                <p><?php echo $trabalho['Firma'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de inicio:</label>
                <p><?php echo $trabalho['Data inicio'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de fim:</label>
                <p><?php echo $trabalho['Data fim'] ?></p>
            </div>
           
            &nbsp;
            <p></p>
            <div class="clear separator"></div>
            &nbsp;
            <p></p>
        <?php endforeach; ?>
    </fieldset>
</form>