



<?php if ($_GET['tipo'] == 1): ?>
    <h1>Registo (Autorizações Vermelhas)</h1>
<?php endif; ?>
<?php if ($_GET['tipo'] == 2): ?>
    <h1>Registo (Autorizações Amarelas)</h1>
<?php endif; ?>

<form id="ajaxform1" method="post">
    <fieldset>
        <?php foreach ($trabalhos as $trabalho): ?>
           <?php if(array_key_exists('id',$_GET)): ?>
           <?php if ($trabalho['ID']==$_GET['id']) : ?>
           <?php if ($flashes): ?>
                <ul id="flashes">
                    <?php foreach ($flashes as $flash): ?>
                        <li><?php echo $flash; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
            <div class="field">
                <label style="width: 130px;">Numero:</label>
                <?php if ($_GET['tipo'] == 1): ?>
                    <p style="color: red"><?php echo Utils::stringrpl(3, ' ', Utils::stringAddZero($trabalho['Numero'])); ?></p>
                <?php endif; ?>
                <?php if ($_GET['tipo'] == 2): ?>
                    <p style="color: gold"><?php echo Utils::stringrpl(3, ' ', Utils::stringAddZero($trabalho['Numero'])); ?></p>
                <?php endif; ?>
            </div>
            <div class="field">
                <label style="width: 130px;">Descrição:</label>
                <p><?php echo $trabalho['Descricao'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Firma:</label>
                <p><?php echo $trabalho['Firma'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de inicio:</label>
                <p><?php echo explode(' ',$trabalho['Data inicio'])[0] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data de fim:</label>
                <p><?php echo explode(' ',$trabalho['Data fim'])[0] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Ultimo registo:</label>
                <?php $last=$dao->findUltimoRegisto($trabalho['ID']) ?>
                <p><?php echo $last['data'] ?> as <?php echo $last['hora'] ?></p>
               
            </div>
            <div class="wrapper">
                <input type="hidden" id="<?php echo $trabalho['ID'] ?>" />
                <input type="button" name="save" style="width: 95px" onclick="regisaut_dialog(<?php echo $trabalho['ID'] ?>,<?php echo $_GET['tipo'] ?>);" class="button" value="REGISTAR" class="submit" />
            </div>
            &nbsp;
            <p></p>
            <div class="clear separator"></div>
            &nbsp;
            <p></p>
        <?php endforeach; ?>
    </fieldset>
</form>
<div id="dialog-regis-aut" title="Insira a hora">
    <input type="text" id="hora" style="width: 55px"/><br /><br />
    <div class="field">
        <input style="height: 20px; width: 30px" onclick="set_hora('01')" id="1" type="button" value="01"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('02')" id="2" type="button" value="02"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('03')" id="3" type="button" value="03"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('04')" id="4" type="button" value="04"/>
        <br />
        <input style="height: 20px;width: 30px" onclick="set_hora('05')" id="5" type="button" value="05"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('06')" id="6" type="button" value="06"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('07')" id="7" type="button" value="07"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('08')" id="8" type="button" value="08"/>
        <input style="width: 50px; height: 50px; float: right" onclick="set_minutos('00')" id="certa" type="button" value="00"/>
        <br />
        <input style="height: 20px;width: 30px" onclick="set_hora('09')" id="9" type="button" value="09"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('10')" id="10" type="button" value="10"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('11')" id="11" type="button" value="11"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('12')" id="12" type="button" value="12"/>
        
        <br />
        <input style="height: 20px;width: 30px" onclick="set_hora('13')" id="13" type="button" value="13"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('14')" id="14" type="button" value="14"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('15')" id="15" type="button" value="15"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('16')" id="16" type="button" value="16"/>
        <input style="height: 20px;width: 50px; height: 50px; float: right" onclick="set_minutos('30')" id="meia" type="button" value="30"/>
        <br />
        <input style="height: 20px;width: 30px" onclick="set_hora('17')" id="17" type="button" value="17"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('18')" id="18" type="button" value="18"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('19')" id="19" type="button" value="19"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('20')" id="20" type="button" value="20"/>
        <br />
        <input style="height: 20px;width: 30px" onclick="set_hora('21')" id="21" type="button" value="21"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('22')" id="22" type="button" value="22"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('23')" id="23" type="button" value="23"/>
        <input style="height: 20px;width: 30px" onclick="set_hora('24')" id="24" type="button" value="24"/>
    </div>
</div>