

<h1>Criar novo pedido de trabalho</h1>

<form id="ajaxform1" method="post">
    <fieldset>
        
        <div class="field">
            <label>Unidade:</label>
            <select name="pedido[unidade]"  onchange="subPedidoSelect(this);">
                <?php foreach ($unidades as $unidade): ?>
                <option 
                    <?php 
                      if(array_key_exists('unidade', $_GET)) if($_GET['unidade']==$unidade['id']) echo ' selected '; 
                    ?> 
                    value="<?php echo $unidade['id'] ?>"><?php echo $unidade['designacao'];?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label>Equipamento:</label>
            <select name="pedido[equipamento]">
                <?php foreach ($equipamentos as $equipamento): ?>
                <option 
                    value="<?php echo $equipamento['id'] ?>"><?php echo $equipamento['Equipamento'];?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
         <div class="field">
            <label>Prioridade:</label>
            <select name="pedido[prioridade]">
                <option value="1">Normal</option>
                <option value="2">Urgente</option>
                <option value="3">Emergente</option>
            </select>
        </div>
        
        <div class="field">
            <label>Descrição:</label>
            <textarea name="pedido[descricao]" cols="1" rows=" 1" style="width:400px" class="<?php echo error_field('texto', $errors); ?>"><?php if(array_key_exists('firma', $_GET)) echo $_POST['autorizacao']['texto'];elseif(array_key_exists('edit', $_GET)) echo Utils::escape($autorizacao->getTexto());?></textarea>
        </div>
        <div class="wrapper">
            
            <input type="submit" onclick="novo_pedido();" name="save" value="Salvar" style="background-image: url(img/buttons/save.png);" class="button" />
        </div>
    </fieldset>
</form>

<div id="dialog-nova-firma" title="Insira nome da firma">
    <input  type="text" name="firma" id="firma" class="text"/> 
</div>