<h1>Pedidos de trabalho sem nota!</h1>


<form id="ajaxform1" method="post">
    <fieldset>
        <?php foreach ($pendentes as $pendente): ?>
            <div class="field">
                <label style="width: 130px;">Unidade:</label>
                <p><?php echo $pendente['designacao'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Equipamento:</label>
                <p><?php echo $pendente['equipamento'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Data:</label>
                <p><?php echo $pendente['data'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Prioridade:</label>
                <p><?php echo $pendente['prioridade'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Pedido por:</label>
                <p><?php echo $pendente['utilizador'] ?></p>
            </div>
            <div class="field">
                <label style="width: 130px;">Descrição:</label>
                <p><?php echo $pendente['descricao'] ?></p>
            </div>
           
            &nbsp;
            <p></p>
            <hr size=1>
            &nbsp;
            <p></p>
        <?php endforeach; ?>
    </fieldset>
</form>