<form action="#" method="post">
    <fieldset>
        <div class="field">
            <label>Descrição:</label>
            <input type="text" name="autorizacao[numero]" value="<?php echo Utils::escape($autorizacao->getNumero()); ?>"
                   class="text<?php echo error_field('numero', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Equipamento:</label>
            <select name="autorizacao[tipo]">
                <option value="1">Vermelha</option>
                <option value="2">Amarela</option>
            </select>
        </div>
        <div class="field">
            <label>Texto:</label>
            <select name="autorizacao[firma]">
            <?php $firmas = new firmaDao();
                  foreach ($firmas->getFirmas() as $firma):
            ?>
                <option value="<?php echo $firma->getID(); ?>"><?php echo $firma->getNome(); ?></option>
             <?php endforeach; ?>       
            </select>
        </div>
        <div class="field">
            <label>Validade:</label>
             <input type="text" style="width: 68px" name="autorizacao[dataInicio]" id="data" value="<?php echo Utils::escape($dueOn->format('Y-n-j'));  ?>" 
                    class="text datepicker"/>
             &nbsp;
            <select name="autorizacao[dataFim]">
                <option>7</option>
                <option>30</option>
            </select>
             &nbsp;
             Dias
        </div>
        
        <div class="field">
            <label>Descrição:</label>
            <textarea name="autorizacao[texto]" cols="1" rows="1"
                      class="<?php echo error_field('texto', $errors); ?>"></textarea>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCELAR" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'EDITAR' : 'ADICIONAR'; ?>" class="submit" />
        </div>
    </fieldset>
</form>